// V3KTR step icons (v0.29.0). GENERATED by scripts/build-step-icons.mjs from its ASCII grids: don't edit here.
// Four 12×12 pixel icons for the four steps (bring · depth · stack · out), for the apps. Drawn for the site's "How it works" (which uses
// animated scenes instead); in the apps: empty states, first-run hints. currentColor, crisp edges, neutral: tint them with the surface's
// colour. Each moving part is a <g class> for CSS animation; the markup is the rest frame. Draw at a multiple of 12px.
//   stepIconSvg('depth', 48)                    → labelled with the step's title (role="img")
//   stepIconSvg('depth', 48, { decorative: true }) → aria-hidden, when the step's text sits beside it
export const STEP_ICONS = {
  "bring": {
    "title": "Bring an image or clip",
    "inner": "<g class=\"frame\"><path d=\"M1 4h3v1h-3zM8 4h3v1h-3zM1 5h1v1h-1zM10 5h1v1h-1zM1 6h1v1h-1zM10 6h1v1h-1zM1 7h1v1h-1zM10 7h1v1h-1zM1 8h1v1h-1zM10 8h1v1h-1zM1 9h1v1h-1zM10 9h1v1h-1zM1 10h1v1h-1zM10 10h1v1h-1zM1 11h10v1h-10z\"/></g><g class=\"tile\"><path d=\"M4 0h4v1h-4zM4 1h4v1h-4zM4 2h4v1h-4z\"/></g>"
  },
  "depth": {
    "title": "Depth is read",
    "inner": "<g class=\"layer-3\"><path d=\"M1 1h7v1h-7zM1 2h1v1h-1zM7 2h1v1h-1zM1 3h1v1h-1zM1 4h1v1h-1zM1 5h1v1h-1zM1 6h1v1h-1zM1 7h2v1h-2z\"/></g><g class=\"layer-2\"><path d=\"M3 3h7v1h-7zM3 4h1v1h-1zM9 4h1v1h-1zM3 5h1v1h-1zM3 6h1v1h-1zM3 7h1v1h-1zM3 8h1v1h-1zM3 9h2v1h-2z\"/></g><g class=\"layer-1\"><path d=\"M5 5h7v1h-7zM5 6h7v1h-7zM5 7h7v1h-7zM5 8h7v1h-7zM5 9h7v1h-7zM5 10h7v1h-7zM5 11h7v1h-7z\"/></g>"
  },
  "stack": {
    "title": "Stack or roll",
    "inner": "<g class=\"die\"><path d=\"M0 0h12v1h-12zM0 1h1v1h-1zM11 1h1v1h-1zM0 2h1v1h-1zM11 2h1v1h-1zM0 3h1v1h-1zM11 3h1v1h-1zM0 4h1v1h-1zM11 4h1v1h-1zM0 5h1v1h-1zM11 5h1v1h-1zM0 6h1v1h-1zM11 6h1v1h-1zM0 7h1v1h-1zM11 7h1v1h-1zM0 8h1v1h-1zM11 8h1v1h-1zM0 9h1v1h-1zM11 9h1v1h-1zM0 10h1v1h-1zM11 10h1v1h-1zM0 11h12v1h-12z\"/></g><g class=\"face-3\"><path d=\"M2 2h2v1h-2zM2 3h2v1h-2zM5 5h2v1h-2zM5 6h2v1h-2zM8 8h2v1h-2zM8 9h2v1h-2z\"/></g><g class=\"face-1\" visibility=\"hidden\"><path d=\"M5 5h2v1h-2zM5 6h2v1h-2z\"/></g><g class=\"face-5\" visibility=\"hidden\"><path d=\"M2 2h2v1h-2zM8 2h2v1h-2zM2 3h2v1h-2zM8 3h2v1h-2zM5 5h2v1h-2zM5 6h2v1h-2zM2 8h2v1h-2zM8 8h2v1h-2zM2 9h2v1h-2zM8 9h2v1h-2z\"/></g>"
  },
  "out": {
    "title": "Take it out",
    "inner": "<g class=\"frame\"><path d=\"M0 2h6v1h-6zM0 3h1v1h-1zM5 3h1v1h-1zM0 4h1v1h-1zM0 5h1v1h-1zM0 6h1v1h-1zM0 7h1v1h-1zM0 8h1v1h-1zM5 8h1v1h-1zM0 9h6v1h-6z\"/></g><g class=\"tile\"><path d=\"M4 4h4v1h-4zM4 5h4v1h-4zM4 6h4v1h-4zM4 7h4v1h-4z\"/></g><g class=\"arrow\"><path d=\"M9 3h1v1h-1zM10 4h1v1h-1zM11 5h1v1h-1zM11 6h1v1h-1zM10 7h1v1h-1zM9 8h1v1h-1z\"/></g>"
  }
};
export function stepIconSvg(name, size = 48, { decorative = false } = {}) {
  const s = STEP_ICONS[name];
  if (!s) return '';
  const a11y = decorative ? 'aria-hidden="true"' : `role="img" aria-label="${s.title}"`;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 12" width="${size}" height="${size}" fill="currentColor" shape-rendering="crispEdges" ${a11y}>${s.inner}</svg>`;
}
