// Self-hosted fonts (v0.33.0, CONNECTIVITY / KOMPOSITOR K21 request): the apps and the engine core load JetBrains Mono
// and Manrope from here instead of Google Fonts, so they work offline and make no third-party font request.
// Copies the woff2 files (latin + latin-ext) from @fontsource 5.3.0 in a DIMENSOR checkout and writes fonts/fonts.css.
//   node scripts/build-fonts.mjs
// Weights: what the apps actually use (PROCESSOR's Google URL: mono 400/500/600, Manrope 400–800), plus mono 700,
// which the link light, the badge and the section labels set and Google was synthesising.
import { copyFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
const src = (pkg) => { for (const repo of ['V3KTR-dimensor', 'V3KTR-dimensor-wt']) { try { return dirname(createRequire(`file:///D:/00%20CLAUDE%20APPS/${repo}/package.json`).resolve(`@fontsource/${pkg}/package.json`)); } catch (e) {} } throw new Error(`@fontsource/${pkg} not found in a DIMENSOR checkout`); };
const OUT = new URL('../fonts/', import.meta.url);
mkdirSync(OUT, { recursive: true });
const RANGES = {   // @fontsource's own subsets
  latin: 'U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2191,U+2193,U+2212,U+2215,U+FEFF,U+FFFD',
  'latin-ext': 'U+0100-02BA,U+02BD-02C5,U+02C7-02CC,U+02CE-02D7,U+02DD-02FF,U+0304,U+0308,U+0329,U+1D00-1DBF,U+1E00-1E9F,U+1EF2-1EFF,U+2020,U+20A0-20AB,U+20AD-20C0,U+2113,U+2C60-2C7F,U+A720-A7FF',
};
const FAMILIES = [['JetBrains Mono', 'jetbrains-mono', [400, 500, 600, 700], 'OFL-JetBrainsMono.txt'], ['Manrope', 'manrope', [400, 500, 600, 700, 800], 'OFL-Manrope.txt']];
let css = `/* V3KTR fonts (generated by scripts/build-fonts.mjs; don't edit). Self-hosted, SIL OFL 1.1 (licences beside the files).
   Pull the whole fonts/ folder next to this sheet and link it before tokens.css; drop the Google Fonts <link>s.
   The names match tokens.css --sans / --mono, so nothing else changes. Preload the two the first paint needs:
   <link rel="preload" href="fonts/manrope-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin>
   <link rel="preload" href="fonts/jetbrains-mono-latin-400-normal.woff2" as="font" type="font/woff2" crossorigin> */\n`;
for (const [family, pkg, weights, lic] of FAMILIES) {
  const dir = src(pkg);
  copyFileSync(join(dir, 'LICENSE'), new URL(lic, OUT));
  for (const w of weights) for (const s of ['latin-ext', 'latin']) {
    const f = `${pkg}-${s}-${w}-normal.woff2`;
    copyFileSync(join(dir, 'files', f), new URL(f, OUT));
    css += `@font-face{font-family:'${family}';font-style:normal;font-weight:${w};font-display:swap;src:url(${f}) format('woff2');unicode-range:${RANGES[s]};}\n`;
  }
}
writeFileSync(new URL('fonts.css', OUT), css);
console.log('fonts/: fonts.css + woff2 (JetBrains Mono 400–700, Manrope 400–800; latin + latin-ext)');
